import { Product } from "@shared/api";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Handcrafted Wooden Coffee Table",
    price: 25999,
    originalPrice: 32999,
    description:
      "Beautiful handcrafted wooden coffee table made from premium teak wood. Perfect for modern living rooms.",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    category: "Furniture",
    subcategory: "Tables",
    rating: 4.8,
    reviews: 156,
    badges: ["Best Seller", "Premium Quality"],
    isCustomizable: true,
    isDIY: false,
    isInstagramPick: true,
    isHandmade: true,
    isNew: false,
    isTrending: true,
    materials: ["Teak Wood", "Metal Hardware"],
    colors: ["Natural Brown", "Dark Walnut"],
    sizes: ["Medium", "Large"],
    tags: ["furniture", "table", "wooden", "handmade", "premium"],
    stock: 15,
    deliveryDays: 7,
    sellerId: "seller_123",
    warranty: {
      period: "2 years",
      description: "Comprehensive warranty covering manufacturing defects",
      type: "manufacturer",
    },
    returnPolicy: {
      returnable: true,
      period: "30 days",
      conditions: [
        "Original packaging",
        "No damage",
        "Assembly instructions included",
      ],
    },
    careInstructions: [
      "Dust regularly with soft cloth",
      "Avoid direct sunlight",
      "Use coasters for drinks",
    ],
    dimensions: {
      length: 120,
      width: 60,
      height: 45,
      weight: 25,
      unit: "cm",
    },
    sku: "WCT-001",
    brand: "CraftMaster",
    vendor: {
      name: "WoodWorks Studio",
      location: "Bangalore",
      rating: 4.9,
    },
    certifications: ["FSC Certified", "VOC Free"],
    sustainabilityInfo: "Made from sustainably sourced wood",
    origin: "India",
    inStock: true,
    lowStockThreshold: 5,
    seoTitle: "Premium Handcrafted Wooden Coffee Table - Teak Wood",
    seoDescription:
      "Buy premium handcrafted wooden coffee table made from teak wood. Perfect for modern homes.",
    faq: [
      {
        question: "What type of wood is used?",
        answer: "We use premium grade teak wood sourced sustainably.",
      },
      {
        question: "Is assembly required?",
        answer:
          "Minimal assembly required. All tools and instructions included.",
      },
    ],
  },
  {
    id: 2,
    name: "Organic Cotton Bedsheet Set",
    price: 3499,
    originalPrice: 4999,
    description:
      "Luxurious organic cotton bedsheet set with premium thread count. Includes bedsheet, pillowcases, and cushion covers.",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg"],
    category: "Home & Living",
    subcategory: "Bedding",
    rating: 4.6,
    reviews: 89,
    badges: ["Organic", "Best Value"],
    isCustomizable: false,
    isDIY: false,
    isInstagramPick: false,
    isHandmade: false,
    isNew: true,
    isTrending: false,
    materials: ["Organic Cotton"],
    colors: ["White", "Cream", "Light Blue", "Sage Green"],
    sizes: ["Queen", "King"],
    tags: ["bedsheet", "organic", "cotton", "bedding", "home"],
    stock: 32,
    deliveryDays: 3,
    sellerId: "seller_123",
    warranty: {
      period: "1 year",
      description: "Quality guarantee against manufacturing defects",
      type: "seller",
    },
    returnPolicy: {
      returnable: true,
      period: "15 days",
      conditions: ["Unused", "Original packaging", "No stains"],
    },
    careInstructions: [
      "Machine wash cold",
      "Tumble dry low",
      "Iron on medium heat",
    ],
    dimensions: {
      length: 220,
      width: 240,
      height: 2,
      weight: 1.5,
      unit: "cm",
    },
    sku: "OCB-002",
    brand: "EcoLiving",
    origin: "India",
    inStock: true,
    lowStockThreshold: 10,
    seoTitle: "Organic Cotton Bedsheet Set - Premium Quality",
    seoDescription:
      "Luxurious organic cotton bedsheet set with high thread count. Perfect for comfortable sleep.",
    faq: [
      {
        question: "What's the thread count?",
        answer:
          "Our bedsheets have a premium 300 thread count for ultimate comfort.",
      },
    ],
  },
  {
    id: 3,
    name: "Ceramic Plant Pot with Drainage",
    price: 899,
    description:
      "Modern ceramic plant pot with built-in drainage system. Perfect for indoor plants and herbs.",
    image: "/placeholder.svg",
    images: ["/placeholder.svg"],
    category: "Garden & Plants",
    subcategory: "Planters",
    rating: 4.4,
    reviews: 34,
    badges: ["Eco-Friendly"],
    isCustomizable: false,
    isDIY: false,
    isInstagramPick: true,
    isHandmade: true,
    isNew: false,
    isTrending: false,
    materials: ["Ceramic", "Cork"],
    colors: ["White", "Terracotta", "Black"],
    tags: ["planter", "ceramic", "garden", "indoor", "plants"],
    stock: 8,
    deliveryDays: 5,
    sellerId: "seller_123",
    returnPolicy: {
      returnable: true,
      period: "7 days",
      conditions: ["No damage", "Original packaging"],
    },
    careInstructions: ["Clean with damp cloth", "Avoid harsh chemicals"],
    dimensions: {
      length: 15,
      width: 15,
      height: 18,
      weight: 0.8,
      unit: "cm",
    },
    sku: "CPP-003",
    brand: "GreenSpace",
    origin: "India",
    inStock: true,
    lowStockThreshold: 3,
  },
];

export const mockSellerStats = {
  totalRevenue: 125000,
  monthlyRevenue: 28500,
  totalProducts: 3,
  totalOrders: 47,
  pendingOrders: 3,
  completedOrders: 44,
  lowStockProducts: 1,
};
